# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "server" do |server|
    server.vm.box = "sip2world-server"
    server.vm.network "forwarded_port", guest: 80, host: 8080
    server.vm.network "forwarded_port", guest: 8000, host: 8000
    server.vm.network "private_network", ip: "192.168.217.100"
 
  end

  config.vm.define "client" do |client|
    client.vm.box = "sip2world-client"
    client.vm.network "private_network", ip: "192.168.217.101"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end

end
